steps:
- name: golang:1.24-alpine
  args:
  - sh
  - -c
  - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /workspace v1.55.2
- name: golang:1.24-alpine
  args:
  - go
  - mod
  - tidy
- name: golang:1.24-alpine
  args:
  - /workspace/golangci-lint
  - run
  env:
  - 'CGO_ENABLED=0'
- name: golang:1.24-alpine
  args:
  - go
  - test
  - ./gpx
  - ./gpxutil
  env:
  - 'CGO_ENABLED=0'
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - '--build-arg'
  - 'GIT_HASH=$SHORT_SHA'
  - '--build-arg'
  - 'GIT_TAG=$TAG_NAME'
  - -t
  - $_IMAGE_NAME
  - .
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - $_IMAGE_NAME
- name: gcr.io/cloud-builders/gcloud
  args:
  - run
  - deploy
  - $_SERVICE_NAME
  - --image=$_IMAGE_NAME
  - --region=$_REGION
  - --platform=managed
  - --update-env-vars=ELEVATION_URL=$_ELEVATION_URL,ELEVATION_TOKEN=$_ELEVATION_TOKEN
