name: Continuous Integration

on:
  pull_request:

env:
  GO_VERSION: '1.24'
  NODE_VERSION: '18'

jobs:
  build-image-and-test:
    name: Build Docker Image (PR Validation)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get Git information
      id: git
      run: |
        echo "hash=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "tag=$(git describe --tags --exact-match 2>/dev/null || echo "")" >> $GITHUB_OUTPUT
        fi

    - name: Build Docker image (no push)
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: false
        tags: pr-${{ github.event.number }}
        build-args: |
          GIT_HASH=${{ steps.git.outputs.hash }}
          GIT_TAG=${{ steps.git.outputs.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
